// eslint-disable-next-line
module.exports = [
  { number: '{1}', name: '{姓名}' },
  { number: '{2}', name: '{姓名+先生/女士}' },
  { number: '{3}', name: '{生日日期}' },
  { number: '{4}', name: '{生日天数}' },
  { number: '{5}', name: '{关注日期}' },
  { number: '{6}', name: '{关注天数}' },
  { number: '{7}', name: '{主门店品牌名称}' },
  { number: '{8}', name: '{主门店名称}' },
  { number: '{9}', name: '{主门店电话}' },
  { number: '{10}', name: '{专属导购姓名}' },
  { number: '{11}', name: '{专属导购手机号}' },
  { number: '{12}', name: '{开卡日期}' },
  { number: '{13}', name: '{开卡天数}' },
  { number: '{14}', name: '{开卡门店名称}' },
  { number: '{15}', name: '{会员卡号}' },
  { number: '{16}', name: '{会员等级名称}' },
  { number: '{17}', name: '{主门店地址}' },
  { number: '{18}', name: '{会员等级剩余有效天数}' },
  { number: '{19}', name: '{积分余额}' },
  { number: '{20}', name: '{30天内将过期积分额度}' },
  { number: '{21}', name: '{储值余额}' },
  { number: '{22}', name: '{消费总额}' },
  { number: '{23}', name: '{消费次数}' },
  { number: '{24}', name: '{最近消费日期}' },
  { number: '{25}', name: '{最近消费间隔}' },
  { number: '{26}', name: '{最高单笔消费}' },
  { number: '{27}', name: '{最近消费门店名称}' },
  { number: '{28}', name: '{最近消费品牌名称}' }
];
